# configmap
application_properties:
  quarkus:
    log:
      level: ERROR
      category:
        infocert:
          level: DEBUG
      console:
        format: "%X{tenantId} %X{userId} %X{InfoCert-Correlation-ID} %d{HH:mm:ss} %-5p [%c{2.}]] (%t) %s%e%n"
  dp_quarkus_api:
    keycloak:
      server_url: https://keycloak.eu-west-1.tsaws.infocert.it/auth
      client_id: midpki
      username: dp_quarkus_api
      user_initial_password: test
      realm: iot
      midpki_client_scope: midpki
    openpolicy:
      bundle_file_name: bundle.tar.gz # the name of the bundle file

ui:
  mimetypes: /etc/nginx/mime.types
  root: /usr/share/nginx/html
  port: 80
  oidc:
    admin:
      uri: https://apitest.infocert.digital/iot/rest/v1/oidc
  resources:
    limits:
      cpu: "100m"
      memory: "50M"
    requests:
      cpu: "50m"
      memory: "50M"

# deployment
app_name: dp_quarkus_api
container_name:
  svc: dp_quarkus_api
  download_opa_bundle: download-opa-bundle

ecrimage:
  svc:
    name: 956251722582.dkr.ecr.eu-west-1.amazonaws.com/iot-mpkiot-useradmin-svts/platform-automation/dp_quarkus_api
    force_version: false
  ui:
    name: 956251722582.dkr.ecr.eu-west-1.amazonaws.com/iot-mpkiot-useradmin-svts/platform-automation/demoportal_fe
    force_version: false
  liquibase:
    name: 956251722582.dkr.ecr.eu-west-1.amazonaws.com/iot-mpkiot-useradmin-svts/platform-automation/useradmin-liquibase
    force_version: false
  sqs_sidecar: "956251722582.dkr.ecr.eu-west-1.amazonaws.com/iot-mpkiot-queuedispatcher-svts/platform-automation/queuedispatcher:1.0.11"
java_args: "-agentlib:jdwp=transport=dt_socket,server=y,address=*:8000,suspend=n"
apigateway: "internal-svts-eks-factory-private-alb-1430683812.eu-west-1.elb.amazonaws.com"

