kind: ConfigMap
apiVersion: v1
metadata:
  name: useradminsvc-configmap
  labels:
    {{- range $key, $val := .Values.metadata.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
data:

  nginx.conf: |-
    events {}
    http {
        include {{ .Values.fe.mimetypes }};
        server {
            listen      {{ .Values.fe.port }};
    
            root {{ .Values.few.root }};
            index index.html;
            location / {
                try_files $uri$args $uri$args/ /index.html;
            }
            location = /basic_status {
                stub_status;
            }
        }
    }
 