apiVersion: v1
kind: Service
metadata:
  name: dp_quarkus_api-service
  labels:
    {{- range $key, $val := .Values.metadata.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app_name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: api
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.ui.port }}
    name: console
