apiVersion: v1
kind: Service
metadata:
  name: demoportal-fe-service
  labels: demoportal-fe-service
spec:
  type: ClusterIP
  selector:
    app: demoportal-fe-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: backend-api
  - protocol: TCP
    port: 80
    targetPort: 80
    name: frontend-angular

----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: demoportal-be-service
  labels: demoportal-be-service
spec:
  type: ClusterIP
  selector:
    app: demoportal-be-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: backend-service
