apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demoportal
  name: demoportal-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoportal-be
  template:
    metadata:
      labels:
        app: demoportal-be
    spec:
      containers:
      - image: 444170698423.dkr.ecr.eu-west-1.amazonaws.com/demoportal-be:0.4
        name: demoportal-be
        env:
          - name: QUARKUS_LOG_LEVEL
            value: DEBUG
          - name: QUARKUS_REST_CLIENT_LOGGING_SCOPE
            value: request-response
          - name: QUARKUS_REST_CLIENT_LOGGING_BODY_LIMIT
            value: "5000"
          - name: QUARKUS_HTTP_CORS
            value: "true"
          - name: QUARKUS_HTTP_CORS_ORIGINS
            value: /.*/
          - name: QUARKUS_TLS_TRUST_ALL
            value: "true"
          - name: QUARKUS_REST_CLIENT_SelfQClient_URL
            value: https://top-stage.infocert.it/nomtom/top/services
          - name: QUARKUS_REST_CLIENT_SelfQRCode_URL
            value: https://apistage.infocert.digital/idengine/api/v1
          - name: QUARKUS_REST_CLIENT_IdentificationFrameworkService_URL
            value: https://apistage.infocert.digital
          - name: QUARKUS_REST_CLIENT_OnboardingWidget_URL
            value: https://apistage.infocert.digital/
          - name: QUARKUS_OIDC_CLIENT_TOKEN_PATH
            value: https://idpstage.infocert.digital/auth/realms/delivery/protocol/openid-connect/token
          - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
            value: demoportal01
          - name: QUARKUS_OIDC_CLIENT_CREDENTIAL_SECRET
            value: a458e0f0-815b-4a72-9203-73de515b4323
          - name: QUARKUS_REST_CLIENT_isacadmin_URL
            value: https://idp.eu-south-1.tsaws.infocert.it/admin/api/1.0.0
          - name: smallrye.jwt.sign.key.location
            value: rsaPrivateKey.pem
          - name: QUARKUS_DATASOURCE_DB_KIND
            value: postgresql
          - name: QUARKUS_DATASOURCE_USERNAME
            value: demoportal_db_user
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: demoportal_db_password 
          - name: QUARKUS_DATASOURCE_DB_VERSION
            value:  "17.0"
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://postgres:5432/demoportal_schema
          - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
            value: "10"
          - name: QUARKUS_HIBERNATE_ORM_ADTABASE_GENERATION 
            value:  update
          - name: QUARKUS_HIBERNATE_ORM_LOG_FORMAT_SQL
            value:  "true"
          - name: QUARKUS_HIBERNATE_ORM_LOG_SQL 
            value:  "true"
          - name: QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT 
            value:  import.sql
          - name: QUARKUS_OIDC_AUTH_SERVER_URL
            value: https://idpcl.infocert.it
          - name: QUARKUS_OIDC_AUTHENTICATION_PKCE_REQUIRED
            value: "true"
          - name: QUARKUS_OIDC_AUTHENTICATION_REDIRECT_PATH
            value: http://localhost:4200
          - name: QUARKUS_OIDC_CLIENT_ID
            value: demoportal_backend
          - name: QUARKUS_OIDC_CREDENTIALS.CLIENT_SECRET.VALE
            value: E%QQH@6C%T#jXXhN
          - name: QUARKUS_OIDC_APPLICATION_TYPE
            value: web-app
          - name: QUARKUS_REST_CLIENT_LOKALISESERVICES_URL
            value: https://api.lokalise.com/api2/projects/6366788662792bacc120a5.07287911/keys?disable_references=1&include_comments=0&include_screenshots=0&include_translations=1
          - name: QUARKUS_SCHEDULER_CRON_TYPE
            value: unix
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: demoportal
  name: demoportal-be-service
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: demoportal-be
  type: NodePort
