apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demoportal
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
