apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demoportal
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql17