Parameters:

  Environment:
    Description: An identifier for the environment. Use value already set in the config
    Type: String

  Team:
    Description: An identifier for the team.
    Type: String

  Project:
    Description: An identifier for the project.
    Type: String

  Component:
    Description: An identifier fot the component.
    Type: String

Conditions:
  Never: !Equals [ a, b ]

Resources:

  NullResource:
    Type: Custom::Null
    Condition: Never
